### ISSUE TITLE
其他镜像站基于http从mirrors-tk同步可行吗

### ISSUE THREAD

**Issue by heheda123123** [mirrors-tk/feedback#14]
https://github.com/sjtug/mirror-requests/issues/79

**Comment by Arnie97** [comment]
我不理解，这相比直接从 HTTP 上游同步有什么优势

**Comment by heheda123123** [comment]
> 我不理解，这相比直接从 HTTP 上游同步有什么优势

貌似没优势，只是说用http同步遇到过被上游封ip的情况

**Comment by Arnie97** [comment]
看 sjtug 已经取得上游同意并用 apt-mirror 完成同步，本问题先关闭了
